steps: 
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops']  # Build the Docker image 
images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'                      # Uplods the Docker image  Registry 