apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  labels:
    app: gcp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/kodekloud-gcp-training/gcpdevops
        ports:
        - containerPort: 5000
